use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :hadithi_api, HadithiApiWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Configure your database
config :hadithi_api, HadithiApi.Repo,
  hostname: System.get_env("DATABASE_HOST") || "localhost",
  username: System.get_env("DATABASE_USER") || "postgres",
  password: System.get_env("DATABASE_PASS") || "postgres",
  database: "hadithi_api_dev",
  pool_size: 10

config :hadithi_api, :generators,
  migration: true,
  binary_id: true

# Twitter API configuration
config :hadithi_api, HadithiApi.Twitter,
  consumer_key: "bhwQC845gDlTUE10ON3ydOfVz",
  consumer_secret: "Gq3KO1GIGtocSYYdjaf0DNjgOiexBgjWmeNEb0eF2JIXWT7ec0",
  token: "",
  token_secret: ""

config :cors_plug,
  origin: ["http://localhost:3000", "http://127.0.0.1:3000"]
